### ISSUE TITLE
Wrong input format, in both cases

### ISSUE THREAD

**Issue by bmix** [petronny/pvz_converter#1]
Hi, thanks for trying to fix the issue with the game. I don't know, how I got my save game (I nearly finnished it on OS X and then got a Windows machine, not sure, whether the save game I have on my Windows machine is the one from the Mac or whether it is already being made by the Windows version) but I tried both directions, first with the `windows` option and then (I use a backup) I tried `mac`. In both cases I get:

`Incorrect input format`

Could that mean, that I already have a correct save file (which would mean, that I have overwritten my backup and started the game out a new)? Maybe you could add a message to the user then? Thanks.

**Comment by petronny** [comment]
Hi, thanks for report.
If you use the Mac saves on a Windows PVZ, PVZ will crash just like it on Mac.
If the saves can be loaded by Windows PVZ, they are definitely Windows version.

But it's weird that both directions fail.
I guess it's because different versions of PVZ use different save format.
Older PVZ doesn't have Zombatars(custom zombies) which will be saved in saves in newer PVZ.
Currently `convert.py` only works with `1.2.0.1073` which means the first byte of the save is `0x0C`.
I can't find the descriptions of old PVZ user file format now. You can send your `users1.dat` to my email `i@jingbei.li` and I will look into it.

**Comment by bmix** [comment]
Never mind! I think I managed to kill my old save file on the cloud anyway ;-/ Thanks four your help!
